"""Emit the M3-6 arena evidence tables (PLAN section 8; TODO M3-6).

Same seeded round-robin the CI integration suite runs, written as a committed
markdown artifact. Deterministic: same tree + config -> same tables. Reproduce with:

  uv run python scripts/arena_run.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from copthief_core.sdk.arena import (  # noqa: E402
    ArenaReport,
    champion_regression,
    load_champions,
    run_round_robin,
)
from copthief_core.sdk.simulation import SimulationSdk  # noqa: E402

ROSTER = ("random", "greedy-manhattan")
SEEDS = range(1, 9)
OUT = Path("docs/evidence/m3-arena.md")


def _tables(report: ArenaReport, champions: dict[str, str], problems: list[str]) -> str:
    lines = [
        "# M3-6 arena - seeded round-robin standings (baseline roster)",
        "",
        "> Generated by `uv run python scripts/arena_run.py` (deterministic; regenerate,",
        "> never hand-edit). Every roster brain plays every roster brain in both roles",
        "> over the same seed set; games run headless through the sdk referee series.",
        f"> Roster: {', '.join(ROSTER)} - seeds {SEEDS.start}..{SEEDS.stop - 1}.",
        "",
        "| brain | role | games | wins | points |",
        "|---|---|---|---|---|",
    ]
    lines += [
        f"| {s.brain} | {s.role} | {s.games} | {s.wins} | {s.points} |" for s in report.standings
    ]
    lines += [
        "",
        f"**Champion pin** (`config/arena_champion.json`): police = "
        f"`{champions['police']}`, thief = `{champions['thief']}`.",
        "",
        (
            "**Regression gate:** GREEN - no brain tops a pinned champion's role table."
            if not problems
            else "**Regression gate: RED**\n\n- " + "\n- ".join(problems)
        ),
        "",
        "Per-pairing outcomes:",
        "",
        "| police brain | thief brain | captures | survivals |",
        "|---|---|---|---|",
    ]
    from copthief_core.domain.rules import Outcome

    lines += [
        f"| {p.police_brain} | {p.thief_brain} "
        f"| {sum(r.outcome is Outcome.COP_CAPTURE for r in p.results)} "
        f"| {sum(r.outcome is Outcome.THIEF_SURVIVAL for r in p.results)} |"
        for p in report.series
    ]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    sdk = SimulationSdk(Path("config"))
    report = run_round_robin(sdk, roster=ROSTER, seeds=SEEDS)
    champions = load_champions(Path("config") / "arena_champion.json")
    problems = champion_regression(report, champions)
    OUT.write_text(_tables(report, champions, problems), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}; gate {'GREEN' if not problems else 'RED'}")
    return 0 if not problems else 1


if __name__ == "__main__":
    raise SystemExit(main())
