"""Emit the arena evidence tables (PLAN section 8; TODO M3-6/M5-2).

Same config-driven round-robin the CI integration suite runs, written as a committed
markdown artifact. Everything quantitative (rosters, seeds, scenario shape, output
path) comes from config/arena.json - per-repo, so this mirrored script stays
role-blind. Deterministic: same tree + config -> same tables. Reproduce with:

  uv run python scripts/arena_run.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from copthief_core.domain.rules import Outcome  # noqa: E402
from copthief_core.sdk.arena import (  # noqa: E402
    ArenaReport,
    champion_regression,
    load_champions,
    run_round_robin,
)
from copthief_core.sdk.arena_config import ArenaConfig, load_arena_config  # noqa: E402
from copthief_core.sdk.simulation import SimulationSdk  # noqa: E402


def _dod_tables(sdk: SimulationSdk, config: ArenaConfig) -> list[str]:
    """One win-rate table per configured DoD series (empty until a role brain lands)."""
    from copthief_core.strategy.scenarios import scenario_suite

    lines: list[str] = []
    for series in config.dod_series:
        scenarios = scenario_suite(
            sdk.constitution, seeds=series.seeds, min_separation=config.scenario_min_separation
        )
        results = sdk.scenario_series(
            police=config.spec_for(series.police),
            thief=config.spec_for(series.thief),
            scenarios=scenarios,
            police_options=config.options_for(series.police),
            thief_options=config.options_for(series.thief),
        )
        winning = Outcome.COP_CAPTURE if series.wins_role == "police" else Outcome.THIEF_SURVIVAL
        wins = sum(r.outcome is winning for r in results)
        rate = wins / len(results)
        verdict = "PASS" if rate >= series.min_win_rate else "FAIL"
        lines += [
            f"**DoD series `{series.label}`** - {series.police} (police) vs "
            f"{series.thief} (thief), {len(results)} scenarios: {series.wins_role} wins "
            f"{wins}/{len(results)} = **{rate:.0%}** (floor {series.min_win_rate:.0%}) - "
            f"**{verdict}**.",
            "",
        ]
    return lines


def _tables(
    report: ArenaReport, config: ArenaConfig, champions: dict[str, str], problems: list[str]
) -> str:
    police_names = ", ".join(e.name for e in config.police_roster)
    thief_names = ", ".join(e.name for e in config.thief_roster)
    lines = [
        "# Arena - config-driven round-robin standings (M5-2)",
        "",
        "> Generated by `uv run python scripts/arena_run.py` (deterministic; regenerate,",
        "> never hand-edit). Per-role rosters over the seeded start-scenario suite",
        "> (config/arena.json); games run headless through the sdk scenario series.",
        f"> Police roster: {police_names}. Thief roster: {thief_names}.",
        f"> Seeds: {', '.join(str(s) for s in config.seeds)} (scenario #1 = signed starts).",
        "",
        "| brain | role | games | wins | points |",
        "|---|---|---|---|---|",
    ]
    lines += [
        f"| {s.brain} | {s.role} | {s.games} | {s.wins} | {s.points} |" for s in report.standings
    ]
    lines += [
        "",
        f"**Champion pin** (`config/arena_champion.json`): police = "
        f"`{champions['police']}`, thief = `{champions['thief']}`.",
        "",
        (
            "**Regression gate:** GREEN - no brain tops a pinned champion's role table."
            if not problems
            else "**Regression gate: RED**\n\n- " + "\n- ".join(problems)
        ),
        "",
        "Per-pairing outcomes:",
        "",
        "| police brain | thief brain | captures | survivals |",
        "|---|---|---|---|",
    ]
    lines += [
        f"| {p.police_brain} | {p.thief_brain} "
        f"| {sum(r.outcome is Outcome.COP_CAPTURE for r in p.results)} "
        f"| {sum(r.outcome is Outcome.THIEF_SURVIVAL for r in p.results)} |"
        for p in report.series
    ]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    config = load_arena_config(Path("config") / "arena.json")
    sdk = SimulationSdk(Path("config"))
    report = run_round_robin(sdk, config=config)
    champions = load_champions(Path("config") / "arena_champion.json")
    problems = champion_regression(report, champions)
    body = _tables(report, config, champions, problems)
    dod = _dod_tables(sdk, config)
    if dod:
        body += "\n" + "\n".join(["## DoD win-rate floors", "", *dod])
    out = Path(config.evidence_out)
    out.write_text(body, encoding="utf-8", newline="\n")
    print(f"wrote {out}; gate {'GREEN' if not problems else 'RED'}")
    return 0 if not problems else 1


if __name__ == "__main__":
    raise SystemExit(main())
