"""Emit the wire-shape balance evidence table (kit issue #6; joint wire-shape ADR).

The same config-driven round-robin as scripts/arena_run.py, played TWICE: hidden
positions (reference-v3 - belief fed by the opponent's locked-model trail) vs common
knowledge (bookletter-v3 - per-step Reveal, TruthFeed certainty deltas). Everything
quantitative comes from config/arena.json (rosters, options, separation) and
config/balance.json (seeds, output path). Deterministic; regenerate, never hand-edit:

  uv run python scripts/balance_run.py
"""

from __future__ import annotations

import json
import sys
from dataclasses import replace
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from copthief_core.domain.rules import Outcome  # noqa: E402
from copthief_core.sdk.arena import ArenaReport, run_round_robin  # noqa: E402
from copthief_core.sdk.arena_config import load_arena_config  # noqa: E402
from copthief_core.sdk.simulation import SimulationSdk  # noqa: E402
from copthief_core.shared.private_config import ConfigError, validated_version  # noqa: E402
from copthief_core.strategy.info_feed import TruthFeed  # noqa: E402


def _load_balance(path: Path) -> tuple[tuple[int, ...], str]:
    """The balance instrument's own knobs (Raises: ConfigError on bad shape)."""
    raw = json.loads(path.read_text(encoding="utf-8"))
    try:
        validated_version(raw, path.name)
        return tuple(int(s) for s in raw["seeds"]), str(raw["evidence_out"])
    except (KeyError, TypeError, ValueError) as error:
        raise ConfigError(f"{path.name}: malformed balance config - {error}") from error


def _cop_wins(report: ArenaReport) -> tuple[int, int]:
    """(cop wins, games) over every pairing series in the report."""
    results = [r for pairing in report.series for r in pairing.results]
    return sum(r.outcome is Outcome.COP_CAPTURE for r in results), len(results)


def _tables(hidden: ArenaReport, full: ArenaReport, seeds: tuple[int, ...]) -> str:
    """The committed markdown: per-pairing cop wins under each wire shape + aggregate."""
    lines = [
        "# Wire-shape balance - hidden (reference-v3) vs common knowledge (bookletter-v3)",
        "",
        "> Generated by `uv run python scripts/balance_run.py` (deterministic; regenerate,",
        "> never hand-edit). Decision support for the joint wire-shape ADR / kit issue #6:",
        "> the shipped arena rosters and seeded scenario suite, played once with positions",
        "> hidden (belief fed by the opponent's honest locked-model trail) and once with",
        "> positions common knowledge (belief collapsed to the revealed true cell before",
        "> every decision). Scope: scent honest per the locked model, verbal layer off in",
        "> both arms - the hint/deception seam is exactly what per-step reveal removes,",
        "> and it is argued in the ADR, not measured here.",
        f"> Seeds: {seeds[0]}..{seeds[-1]} (scenario #1 = signed starts).",
        "",
        "| police brain | thief brain | games | cop wins (hidden) | cop wins (full-info) | delta |",
        "|---|---|---|---|---|---|",
    ]
    for pairing_hidden, pairing_full in zip(hidden.series, full.series, strict=True):
        wins_hidden = sum(r.outcome is Outcome.COP_CAPTURE for r in pairing_hidden.results)
        wins_full = sum(r.outcome is Outcome.COP_CAPTURE for r in pairing_full.results)
        lines.append(
            f"| {pairing_hidden.police_brain} | {pairing_hidden.thief_brain} "
            f"| {len(pairing_hidden.results)} | {wins_hidden} | {wins_full} "
            f"| {wins_full - wins_hidden:+d} |"
        )
    wins_h, games = _cop_wins(hidden)
    wins_f, _ = _cop_wins(full)
    delta_pp = (wins_f - wins_h) / games
    favored = "COP" if wins_f > wins_h else ("THIEF" if wins_f < wins_h else "NEITHER side")
    lines += [
        "",
        f"**Aggregate cop win-rate:** hidden {wins_h}/{games} = **{wins_h / games:.1%}** vs "
        f"full-info {wins_f}/{games} = **{wins_f / games:.1%}** "
        f"(delta {delta_pp:+.1%} points).",
        "",
        "**Reading:** on this config with the shipped brains, the common-knowledge wire",
        f"favors the **{favored}** (negative delta = evader-favored: both sides get perfect",
        "rival tracking, so the roles keep only their positional/structural assets).",
        "Per-pairing deltas localize the shift; the mechanism analysis belongs to the",
        "wire-shape ADR, not this table.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    """Run both arms and write the committed evidence table."""
    arena_cfg = load_arena_config(Path("config") / "arena.json")
    seeds, evidence_out = _load_balance(Path("config") / "balance.json")
    config = replace(arena_cfg, seeds=seeds)
    sdk = SimulationSdk(Path("config"))
    hidden = run_round_robin(sdk, config=config)
    feed = TruthFeed(sdk.constitution, smell_trust=sdk.private.smell_trust_weight)
    full = run_round_robin(sdk, config=config, belief_feed=feed)
    out = Path(evidence_out)
    out.write_text(_tables(hidden, full, seeds), encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
