"""Sweep the cop's claim threshold on expected SERIES POINTS (M7-19; PRD_claims §5.3).

Capture rate is the wrong maximand here: silence trades landing captures for information
denial, and only the scoring table prices that trade. So every cell below is the cop's
points per game under `config/game.json`, and the winner is read per OPPONENT TYPE — the
threshold is private config and counted series are one per opponent, so deployment is a
per-match choice, not one global number.

The sweep is an ordinary arena config whose police roster is the same brain repeated at
different `claim_threshold`s, against a MIXTURE of thieves (some reading claims, some
not). Deterministic - same tree + config -> same table. Reproduce with:

  uv run python scripts/claim_sweep.py --config config/claim_sweep.json --out <file>.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from copthief_core.domain.scoring import ScoringTable, score_mini_game  # noqa: E402
from copthief_core.sdk.arena import ArenaReport, run_round_robin  # noqa: E402
from copthief_core.sdk.arena_config import ArenaConfig, load_arena_config  # noqa: E402
from copthief_core.sdk.simulation import SimulationSdk  # noqa: E402
from copthief_core.strategy.referee import RefereeGameResult  # noqa: E402


def cop_points_per_game(results: tuple[RefereeGameResult, ...], table: ScoringTable) -> float:
    """The cop's mean points per game over one pairing's series (derived, never declared)."""
    if not results:
        return 0.0
    return sum(score_mini_game(r.outcome, table)[0] for r in results) / len(results)


def _points(report: ArenaReport, police: str, thief: str, table: ScoringTable) -> float:
    pairing = next(s for s in report.series if s.police_brain == police and s.thief_brain == thief)
    return cop_points_per_game(pairing.results, table)


def _table(report: ArenaReport, config: ArenaConfig, sdk: SimulationSdk) -> list[str]:
    """One row per police entry, one column per thief arm.

    Rows are grouped by BRAIN SPEC and the per-opponent winner is read within a group:
    thresholds are only comparable across the same weight vector, and mixing two cops
    into one ranking would answer a question this sweep is not asking.
    """
    scoring = sdk.constitution.scoring
    thieves = [entry.name for entry in config.thief_roster]
    lines = [
        "| cop | claim threshold | " + " | ".join(thieves) + " | mean |",
        "|" + "---|" * (len(thieves) + 3),
    ]
    best: dict[tuple[str, str], tuple[str, float]] = {}
    for police in config.police_roster:
        cells = [_points(report, police.name, thief, scoring) for thief in thieves]
        for thief, points in zip(thieves, cells, strict=True):
            key = (police.spec, thief)
            if key not in best or points > best[key][1]:
                best[key] = (police.name, points)
        label = "unmodelled" if police.claim_threshold is None else f"{police.claim_threshold:g}"
        mean = sum(cells) / len(cells) if cells else 0.0
        lines += [
            f"| {police.name} | {label} | "
            + " | ".join(f"{c:.2f}" for c in cells)
            + f" | {mean:.2f} |"
        ]
    lines += [
        "",
        "**Best entry per (weight vector, opponent).** Deployment is per-match, and a "
        "threshold is only meaningful alongside the weight vector it runs under:",
        "",
        "| weight vector | opponent | best entry | cop points/game |",
        "|---|---|---|---|",
    ]
    for (spec, thief), (entry, points) in best.items():
        lines.append(f"| `{spec}` | {thief} | {entry} | {points:.2f} |")
    return lines


def render(report: ArenaReport, config: ArenaConfig, sdk: SimulationSdk, source: str) -> str:
    """The committed markdown artifact for this sweep."""
    scoring = sdk.constitution.scoring
    head = [
        "# Claim-threshold sweep on series points (M7-19)",
        "",
        f"> Generated by `uv run python scripts/claim_sweep.py --config {source}`",
        "> (deterministic; regenerate, never hand-edit).",
        f"> Scent model: {config.scent_model}. Seeds: {len(config.seeds)}.",
        "> Cells are the COP's points per game under the signed scoring table "
        f"(capture {scoring.capture_cop} / survival {scoring.survival_cop}).",
        "> `unmodelled` is the historical physics; `0` is today's emitter "
        "(declare on every moving turn).",
        "",
    ]
    return "\n".join(head + _table(report, config, sdk) + [""])


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    config = load_arena_config(args.config)
    sdk = SimulationSdk(Path("config"))
    report = run_round_robin(sdk, config=config)
    text = render(report, config, sdk, args.config.as_posix())
    if args.out is not None:
        # LF explicitly (ops gotcha #7b): a CRLF artifact hashes differently from the
        # bytes git stores and reddens the mirror check on regeneration.
        args.out.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {args.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
