"""Measure what the capture-claim channel is worth on the REAL peer path (M7-18).

The arena models claim-reading with an information feed; this measures the production
session logic instead. Paired `PeerSession`s play full mini-games, and at every moment
the claim RECEIVER is about to decide, its belief argmax is compared with the claim
SENDER's true current cell. Role-blind: brains and scent model come from the config dir,
so each repo measures its own deployment. Deterministic - same tree + config -> same
numbers. Reproduce with:

  uv run python scripts/claim_probe.py --config config --out docs/evidence/<file>.md

Quantitative inputs (games, seeds, step cap) are CLI arguments, never literals in logic.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, replace
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from copthief_core.domain.state_machine import GameState  # noqa: E402
from copthief_core.peer.session import PeerSession  # noqa: E402
from copthief_core.shared.config import load_all  # noqa: E402


@dataclass
class ProbeTotals:
    """Tracking counters accumulated over every probed game."""

    decisions: int = 0
    exact: int = 0
    claimed_turns: int = 0
    silent_turns: int = 0

    def add(self, other: ProbeTotals) -> None:
        """Fold one game's counters into the running totals."""
        self.decisions += other.decisions
        self.exact += other.exact
        self.claimed_turns += other.claimed_turns
        self.silent_turns += other.silent_turns

    @property
    def exact_rate(self) -> float:
        """Share of decisions taken with the sender's cell known exactly."""
        return self.exact / self.decisions if self.decisions else 0.0


def probe_game(
    config_dir: Path, *, seed: int, step_cap: int, scent_model: str | None = None
) -> ProbeTotals:
    """One paired mini-game (Input: config dir + seed + cap; Output: its counters).

    The sender is the side that emits capture claims; the receiver is the side whose
    belief we score. Which wire role that is follows from the protocol, not from a
    literal here: only a police peer claims, so `sender` is built as police.

    `scent_model` overrides the config's `[scent] model` in memory only, so the physics
    a counted series locks can be probed from the COMMITTED config dir — the shipped
    file is never edited and no local path enters the artifact.
    """
    constitution, private, _limits = load_all(config_dir, counted=False)
    if scent_model is not None:
        private = replace(private, scent_model=scent_model)
    sender = PeerSession(constitution, private, role="police", seed=seed)
    receiver = PeerSession(constitution, private, role="thief", seed=seed + 1)
    receiver.handle_negotiate(sender.negotiate_payload())
    sender.handle_negotiate(receiver.negotiate_payload())

    totals = ProbeTotals()
    now = 1.0
    for _ in range(step_cap):
        if GameState.GAME_OVER in (sender.machine.state, receiver.machine.state):
            break
        sender.handle_receive_turn(receiver.take_turn(now=now))
        now += 0.5
        if sender.machine.state is GameState.GAME_OVER:
            break
        message = sender.take_turn(now=now)
        now += 0.5
        if message["capture_claim"] is None:
            totals.silent_turns += 1
        else:
            totals.claimed_turns += 1
        receiver.handle_receive_turn(message)
        if receiver.machine.state is GameState.GAME_OVER:
            break
        # The receiver is about to decide: does it know where the sender actually is?
        totals.decisions += 1
        if receiver.belief.argmax() == tuple(sender.position):
            totals.exact += 1
    return totals


def run(
    config_dir: Path,
    *,
    games: int,
    first_seed: int,
    step_cap: int,
    scent_model: str | None = None,
) -> ProbeTotals:
    """Accumulate `games` probed mini-games from consecutive seeds."""
    totals = ProbeTotals()
    for offset in range(games):
        totals.add(
            probe_game(
                config_dir,
                seed=first_seed + offset * 2,
                step_cap=step_cap,
                scent_model=scent_model,
            )
        )
    return totals


def render(totals: ProbeTotals, *, config_dir: Path, model: str, games: int) -> str:
    """The committed markdown artifact for this probe."""
    turns = totals.claimed_turns + totals.silent_turns
    silent_share = totals.silent_turns / turns if turns else 0.0
    return "\n".join(
        [
            "# Claim-channel tracking on the peer path (M7-18)",
            "",
            "> Generated by `uv run python scripts/claim_probe.py` "
            "(deterministic; regenerate, never hand-edit).",
            f"> Config: `{config_dir.as_posix()}` · scent model: {model} · games: {games}.",
            "> Measures the claim RECEIVER's belief argmax against the claim SENDER's true",
            "> cell at every moment the receiver is about to decide.",
            "",
            "| metric | value |",
            "|---|---|",
            f"| decisions probed | {totals.decisions} |",
            f"| decisions with the sender's cell known EXACTLY | {totals.exact} |",
            f"| exact-tracking rate | {totals.exact_rate:.3f} |",
            f"| sender turns carrying a claim | {totals.claimed_turns} |",
            f"| sender turns silent (STAY/BARRIER) | {totals.silent_turns} |",
            f"| silent share of sender turns | {silent_share:.3f} |",
            "",
        ]
    )


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=Path("config"))
    parser.add_argument("--games", type=int, required=True)
    parser.add_argument("--first-seed", type=int, required=True)
    parser.add_argument("--step-cap", type=int, required=True)
    parser.add_argument("--scent-model", type=str, default=None)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    _constitution, private, _limits = load_all(args.config, counted=False)
    model = args.scent_model or private.scent_model
    totals = run(
        args.config,
        games=args.games,
        first_seed=args.first_seed,
        step_cap=args.step_cap,
        scent_model=args.scent_model,
    )
    text = render(totals, config_dir=args.config, model=model, games=args.games)
    if args.out is not None:
        # LF explicitly: a CRLF artifact hashes differently from git's stored bytes and
        # silently reddens the mirror check (ops gotcha #7b).
        args.out.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {args.out}")
    print(f"exact-tracking {totals.exact}/{totals.decisions} = {totals.exact_rate:.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
