"""Run the M5-6 template-bank A/B and emit its artifacts (config-driven, role-blind).

Reads config/deception_ab.json (per-repo; absent = this repo does not run the A/B —
exit 0, nothing written) and measures deception efficacy per bank in referee mode:
mean belief-error induced per lie / per truth-hint, plus survival outcomes, over the
configured scenario seeds. Deterministic: same tree + config -> same artifacts.

  uv run python scripts/deception_ab.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from copthief_core.shared.config import load_all, load_gazetteer  # noqa: E402
from copthief_core.shared.private_config import validated_version  # noqa: E402
from copthief_core.strategy.deception_eval import BankResult, run_bank_series  # noqa: E402

CONFIG_PATH = Path("config") / "deception_ab.json"


def _evidence(raw: dict[str, object], results: list[BankResult]) -> str:
    lines = [
        "# M5-6 template-bank A/B - deception efficacy (referee mode)",
        "",
        "> Generated by `uv run python scripts/deception_ab.py` (deterministic;",
        "> regenerate, never hand-edit). Efficacy = mean belief-error induced on the",
        "> tracking belief per hint (error = 1 - P(true cell), the M3-3 identity),",
        "> split by SEALED verdict - measurable only in referee mode, where truth is",
        "> known. Wording is neutral to our own closed-vocabulary parser by",
        "> construction; measured differences come from parse survival under the",
        f"> signed word cap and the decoy policy. Thief: `{raw['thief']}`.",
        "",
        "| bank | games | thief wins | lies | truths | error/lie | error/truth |",
        "|---|---|---|---|---|---|---|",
    ]
    lines += [
        f"| {r.bank} | {r.games} | {r.thief_wins} | {r.summary.lies} | {r.summary.truths} "
        f"| {r.summary.lie_delta:+.4f} | {r.summary.truth_delta:+.4f} |"
        for r in results
    ]
    winner = max(results, key=lambda r: (r.summary.lie_delta, r.thief_wins))
    lines += [
        "",
        f"**Winner (highest induced error per lie, survivals tiebreak): `{winner.bank}`** - "
        "shipped in `game.toml [strategy] hint_bank`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    if not CONFIG_PATH.exists():
        print("deception_ab: not configured in this repo (config/deception_ab.json absent).")
        return 0
    raw = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    validated_version(raw, CONFIG_PATH.name)
    constitution, private, _limits = load_all(Path("config"), counted=False)
    gazetteer = load_gazetteer(
        Path("config") / "gazetteer.json",
        map_area=constitution.world.map_area,
        board=constitution.board.make_board(),
    )
    results = run_bank_series(
        constitution,
        gazetteer=gazetteer,
        police_brain_name=str(raw["police"]),
        thief_brain_name=str(raw["thief"]),
        smell_trust=private.smell_trust_weight,
        hint_trust=private.hint_trust_default,
        seeds=[int(s) for s in raw["seeds"]],
        min_separation=int(raw["scenario_min_separation"]),
        banks=[str(b) for b in raw["banks"]],
        police_options={str(k): float(v) for k, v in raw.get("police_options", {}).items()},
        thief_options={str(k): float(v) for k, v in raw.get("thief_options", {}).items()},
    )
    Path(str(raw["evidence_out"])).write_text(
        _evidence(raw, results), encoding="utf-8", newline="\n"
    )
    winner = max(results, key=lambda r: (r.summary.lie_delta, r.thief_wins))
    print(f"wrote {raw['evidence_out']}; winner: {winner.bank}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
