"""Run the committed offline evolution (M5-4) and emit its artifacts.

Config-driven and role-blind (config/ga.json): evolves the LOCAL repo's role brain
against the fixed reference opponent over a fresh scenario-seed suite. Writes the
weights artifact (config/ga_weights.json) and the fitness-curve evidence table
(docs/evidence/m5-ga.md). Deterministic: same tree + config -> same artifacts.

  uv run python scripts/ga_run.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from copthief_core.strategy.genetic import (  # noqa: E402
    EvolutionResult,
    GaConfig,
    evolve,
    load_ga_config,
)


def _artifact(config: GaConfig, result: EvolutionResult) -> dict[str, object]:
    return {
        "version": "1.00",
        "role": config.role,
        "brain": config.brain,
        "opponent": config.opponent,
        "fitness_seeds": list(config.run.fitness_seeds),
        "default_fitness": result.default_fitness,
        "evolved_fitness": result.best_fitness,
        "evolved_options": result.best_options,
        "history": [{"best": g.best, "mean": g.mean} for g in result.history],
    }


def _evidence(config: GaConfig, result: EvolutionResult) -> str:
    lines = [
        "# M5-4 genetic tuning - offline evolution (fitness curve)",
        "",
        "> Generated by `uv run python scripts/ga_run.py` (deterministic; regenerate,",
        f"> never hand-edit). Fitness = win-rate of the evolved candidate as {config.role}",
        f"> vs `{config.opponent}` over the fresh scenario seeds "
        f"{config.run.fitness_seeds[0]}..{config.run.fitness_seeds[-1]}",
        "> (never the DoD seeds - the gate is not a training target). Elitism makes",
        "> best fitness non-decreasing by construction.",
        "",
        "| generation | best | mean |",
        "|---|---|---|",
    ]
    lines += [
        f"| {index} | {g.best:.3f} | {g.mean:.3f} |"
        for index, g in enumerate(result.history, start=1)
    ]
    improved = "IMPROVING" if result.history[-1].best > result.history[0].best else "FLAT"
    lines += [
        "",
        f"**Default-weights fitness on the same suite:** {result.default_fitness:.3f}.",
        f"**Evolved fitness:** {result.best_fitness:.3f} - curve {improved} "
        f"({result.history[0].best:.3f} -> {result.history[-1].best:.3f}).",
        "",
        "Evolved weights are committed in `config/ga_weights.json`; they deploy only",
        "via config review (never to the sparring host - CLAUDE.md s9).",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    config = load_ga_config(Path("config") / "ga.json")
    result = evolve(config, config.run)
    Path(config.artifact_out).write_text(
        json.dumps(_artifact(config, result), indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    Path(config.evidence_out).write_text(_evidence(config, result), encoding="utf-8", newline="\n")
    print(
        f"wrote {config.artifact_out} + {config.evidence_out}; "
        f"default {result.default_fitness:.3f} -> evolved {result.best_fitness:.3f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
