"""Alternating best-response self-play loop (M11 part 2; instrument, not CI).

Round = EVADER phase (harden doctrine-evader vs the current champion cop +
rival cops) then COP phase (harden PoliceBrain vs the current champion evader +
rival thieves). Every phase's harvest passes the real-opponent pool gate
(scripts/selfplay_gate.py) before it may replace the champion — beating
ourselves while losing to real opponents is the failure mode the gate catches.
Stops early when a full round adopts nothing (plateau). Deterministic: same
tree + configs -> same trajectory.

  uv run python scripts/selfplay_loop.py [--rounds 2]
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from selfplay_gate import pool_gate  # noqa: E402

from copthief_core.sdk.arena_config import load_arena_config  # noqa: E402
from copthief_core.sdk.simulation import SimulationSdk  # noqa: E402
from copthief_core.strategy.genetic import GaConfig, evolve, load_ga_config  # noqa: E402
from copthief_core.strategy.genetic.fitness import fitness  # noqa: E402
from copthief_core.strategy.scenarios import scenario_suite  # noqa: E402

POOL = load_arena_config(Path("config/arena_pool.json"))
CHAMPION_COP = "police-m11"
CHAMPION_EVADER = "doctrine-m11"
FEED = "sharp199"


def _with_target(config: GaConfig, options: dict[str, float]) -> GaConfig:
    """The phase config with the current champion opponent injected at pool head."""
    member = {"spec": config.opponent, "feed": config.opponent_feed, "options": options}
    return dataclasses.replace(config, opponent_pool=(member, *config.opponent_pool))


def _phase(
    sdk: SimulationSdk,
    config_path: str,
    *,
    role: str,
    champion: dict[str, float],
    target_options: dict[str, float],
    lines: list[str],
) -> tuple[dict[str, float], bool]:
    """One GA phase + pool gate. Output: (ruling options, adopted?)."""
    config = _with_target(load_ga_config(Path(config_path)), target_options)
    result = evolve(config, config.run)
    suite = scenario_suite(
        sdk.constitution,
        seeds=list(config.run.fitness_seeds),
        min_separation=config.run.scenario_min_separation,
    )
    champ_fit = fitness(
        config,
        sdk.constitution,
        sdk.private.smell_trust_weight,
        suite,
        dict(champion),
        locked_models=sdk.private.locked_models,
    )
    gate_suite = scenario_suite(
        sdk.constitution, seeds=list(POOL.seeds), min_separation=POOL.scenario_min_separation
    )
    rows, green = pool_gate(
        sdk,
        POOL,
        gate_suite,
        role=role,
        spec=config.brain,
        feed=FEED,
        champion=champion,
        candidate=result.best_options,
        claim_threshold=config.claim_threshold,
        claim_feed=config.claim_feed,
    )
    adopted = green and result.best_fitness > champ_fit
    verdict = (
        f"### {role} phase — fitness {champ_fit:.3f} (champion) vs "
        f"{result.best_fitness:.3f} (candidate); pool gate "
        f"{'GREEN' if green else 'RED'} -> {'ADOPTED' if adopted else 'kept champion'}"
    )
    lines += [
        verdict,
        "",
        "| rival arm | champion wins | candidate wins | holds |",
        "|---|---|---|---|",
        *(f"| {arm} | {c}/32 | {k}/32 | {'YES' if h else 'NO'} |" for arm, c, k, h in rows),
        "",
        f"candidate options: `{json.dumps(result.best_options, sort_keys=True)}`",
        "",
    ]
    print(verdict, flush=True)
    return (dict(result.best_options), True) if adopted else (dict(champion), False)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rounds", type=int, default=2)
    parser.add_argument("--out", default="docs/evidence/m11p2-selfplay.md")
    args = parser.parse_args()
    sdk = SimulationSdk(Path("config"))
    evader = {str(k): float(v) for k, v in POOL.options_for(CHAMPION_EVADER).items()}
    cop = {str(k): float(v) for k, v in POOL.options_for(CHAMPION_COP).items()}
    lines = [
        "# Self-play hardening trajectory (M11 part 2)",
        "",
        "> Generated by `uv run python scripts/selfplay_loop.py` (deterministic;",
        "> regenerate, never hand-edit). Gate suite = `config/arena_pool.json`",
        "> seeds; GA fitness seeds are fresh per phase config. A phase's harvest",
        "> replaces the champion only if the pool gate is green on EVERY arm AND",
        "> its fitness beats the champion's on the identical suite.",
        "",
    ]
    for round_number in range(1, args.rounds + 1):
        lines += [f"## Round {round_number}", ""]
        evader, evader_adopted = _phase(
            sdk,
            "config/ga_selfplay_evader.json",
            role="thief",
            champion=evader,
            target_options=cop,
            lines=lines,
        )
        cop, cop_adopted = _phase(
            sdk,
            "config/ga_selfplay_cop.json",
            role="police",
            champion=cop,
            target_options=evader,
            lines=lines,
        )
        if not (evader_adopted or cop_adopted):
            lines += [f"Round {round_number} adopted nothing — plateau, loop stops.", ""]
            break
    lines += [
        "## Final champions",
        "",
        f"evader: `{json.dumps(evader, sort_keys=True)}`",
        "",
        f"cop: `{json.dumps(cop, sort_keys=True)}`",
        "",
    ]
    Path(args.out).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    for config_path, options in (
        ("config/ga_selfplay_evader.json", evader),
        ("config/ga_selfplay_cop.json", cop),
    ):
        artifact = load_ga_config(Path(config_path)).artifact_out
        payload = {"version": "1.00", "champion_options": options, "source": args.out}
        Path(artifact).write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
        )
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
