"""Solver defer-cause probe (M11-4) — budget-abort vs proven-no-proof (throwaway, not CI).

`endgame_node_cap = 20000` was tuned on chase positions; mid-cage branching is
wider, and the g01 stall was a cousin of exactly this blind-spot class. This
instrument answers ONE question: when the solver defers, is it because no proof
exists inside the horizon (fine), or because the cap starved a proof that was
there (a conversion the config donated)? Method: wrap the brain's solver seam;
on every defer, replay the same position at RESCUE_CAP nodes — a proof found
there is a budget-abort by definition, still-none is (bounded) no-proof.

Zero production churn: the wrap lives here, the shipped brain plays exactly its
capped decision either way. Pattern: scripts/m11_probe.py.
Run: uv run python scripts/solver_defer_probe.py [--out docs/evidence/...]
"""

from __future__ import annotations

import sys
import time
from collections.abc import Mapping
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from copthief_core.domain.board import Board, Coord  # noqa: E402
from copthief_core.sdk.arena_config import load_arena_config  # noqa: E402
from copthief_core.sdk.simulation import SimulationSdk  # noqa: E402
from copthief_core.strategy.scenarios import scenario_suite  # noqa: E402

RESCUE_CAP = 500_000  # 25x the shipped cap; "rescued" below always means at this bound
TALLY = {"calls": 0, "proof": 0, "no_proof": 0, "budget_abort": 0}


def _instrumented(
    board: Board,
    cop: Coord,
    support: list[Coord],
    move_set: tuple[str, ...],
    opts: Mapping[str, float],
    *,
    barriers_used: int,
    max_barriers: int,
) -> tuple[str, str | Coord] | None:
    # Lazy import: a COP-repo instrument, but `scripts/` mirrors whole and the two
    # repos classify `copthief_police` differently for import sorting — module scope
    # stays core-only so the SAME bytes lint green in both trees.
    from copthief_police.endgame import forced_action

    TALLY["calls"] += 1
    got = forced_action(
        board, cop, support, move_set, opts, barriers_used=barriers_used, max_barriers=max_barriers
    )
    if got is not None:
        TALLY["proof"] += 1
        return got
    rescue = forced_action(
        board,
        cop,
        support,
        move_set,
        {**opts, "endgame_node_cap": RESCUE_CAP},
        barriers_used=barriers_used,
        max_barriers=max_barriers,
    )
    TALLY["budget_abort" if rescue is not None else "no_proof"] += 1
    return got  # the shipped cap's decision plays either way


def _arm() -> None:
    """Wrap the brain's solver seam (import lazy for the same mirror-lint reason)."""
    import copthief_police.brain as police_brain_module

    police_brain_module.forced_action = _instrumented


CONFIG = load_arena_config(Path("config/arena_pool.json"))
POLICE = "police-m11"
THIEVES = [entry.name for entry in CONFIG.thief_roster]


def main() -> int:
    _arm()
    sdk = SimulationSdk(Path("config"))
    scenarios = scenario_suite(
        sdk.constitution, seeds=list(CONFIG.seeds), min_separation=CONFIG.scenario_min_separation
    )
    lines = [
        "# Solver defer-cause probe (M11-4)",
        "",
        "> Generated by `uv run python scripts/solver_defer_probe.py` over the",
        "> refreshed pool (`config/arena_pool.json`), police-m11 armed knobs.",
        f"> Every defer replayed at {RESCUE_CAP} nodes: `budget-abort` = proof found",
        "> at the rescue cap (the shipped cap starved it); `no-proof` = still none.",
        "> The load-bearing column is `aborted survivals`: games we did NOT convert",
        "> in which at least one starved proof existed.",
        "",
        "| thief | games | captures | solver calls | proofs | no-proof defers "
        "| budget-abort defers | aborted survivals |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for thief in THIEVES:
        row = {"games": 0, "caps": 0, "calls": 0, "proof": 0, "no_proof": 0, "abort": 0, "bad": 0}
        started = time.perf_counter()
        for scenario in scenarios:
            for key in TALLY:
                TALLY[key] = 0
            game = sdk.scenario_series(
                police=CONFIG.spec_for(POLICE),
                thief=CONFIG.spec_for(thief),
                scenarios=[scenario],
                police_options=CONFIG.options_for(POLICE),
                thief_options=CONFIG.options_for(thief),
                police_feed=next(e.feed for e in CONFIG.police_roster if e.name == POLICE),
                thief_feed=next(e.feed for e in CONFIG.thief_roster if e.name == thief),
                claim_threshold=CONFIG.claim_threshold_for(POLICE),
                thief_claim_feed=next(e.claim_feed for e in CONFIG.thief_roster if e.name == thief),
            )[0]
            captured = game.outcome.value == "cop_capture"
            row["games"] += 1
            row["caps"] += int(captured)
            row["calls"] += TALLY["calls"]
            row["proof"] += TALLY["proof"]
            row["no_proof"] += TALLY["no_proof"]
            row["abort"] += TALLY["budget_abort"]
            row["bad"] += int(not captured and TALLY["budget_abort"] > 0)
        elapsed = time.perf_counter() - started
        print(f"{thief}: {row} ({elapsed:.0f}s)", flush=True)
        lines.append(
            f"| {thief} | {row['games']} | {row['caps']} | {row['calls']} | {row['proof']} "
            f"| {row['no_proof']} | {row['abort']} | {row['bad']} |"
        )
    out = Path("docs/evidence/m11p2-solver-defer.md")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
